version: '3.8'

services:
  go-server:
      image: go-server
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: go-server
      working_dir: /app
      ports:
        - "5000:5000"
      depends_on:
        - postgres-db
      restart: always
  postgres-db:
    image: postgres:15.5-alpine3.18
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  pgbouncer:
    image: edoburu/pgbouncer
    container_name: pgbouncer
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    depends_on:
      - postgres-db