apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - image: huhuhu0420/go-server:version0.1test
        name: go-server
        ports:
        - containerPort: 5000
        env:
        - name: PG_HOST
          value: postgres-db