// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ad": {
            "get": {
                "description": "Get ad array by query",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ads"
                ],
                "summary": "Get ad array by query",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Offset",
                        "name": "Offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Limit",
                        "name": "Limit",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Age",
                        "name": "Age",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "M",
                            "F"
                        ],
                        "type": "string",
                        "description": "Gender",
                        "name": "Gender",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Country",
                        "name": "Country",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "Android",
                            "iOS",
                            "Web"
                        ],
                        "type": "string",
                        "description": "Platform",
                        "name": "Platform",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.AdsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "description": "Create a new ad, the conditions are optional",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ads"
                ],
                "summary": "Create a new ad",
                "parameters": [
                    {
                        "description": "Ad object that needs to be added",
                        "name": "ad",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.AdInfo"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Ad": {
            "description": "A brief advertisement information",
            "type": "object",
            "properties": {
                "endAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-12-01T00:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Ad title"
                }
            }
        },
        "domain.AdInfo": {
            "description": "An advertisement information",
            "type": "object",
            "required": [
                "endAt",
                "startAt",
                "title"
            ],
            "properties": {
                "conditions": {
                    "$ref": "#/definitions/domain.Conditions"
                },
                "endAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-12-01T00:00:00Z"
                },
                "startAt": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2023-01-01T00:00:00Z"
                },
                "title": {
                    "type": "string",
                    "example": "Ad title"
                }
            }
        },
        "domain.AdsResponse": {
            "description": "The response structure containing multiple ads",
            "type": "object",
            "properties": {
                "items": {
                    "description": "An array of ads",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Ad"
                    }
                }
            }
        },
        "domain.Conditions": {
            "description": "The conditions for getting ads",
            "type": "object",
            "properties": {
                "ageEnd": {
                    "type": "integer",
                    "example": 65
                },
                "ageStart": {
                    "type": "integer",
                    "example": 18
                },
                "country": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "US"
                    ]
                },
                "gender": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "M"
                    ]
                },
                "platform": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "Android"
                    ]
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Advertising ServiceAPI",
	Description:      "This is a simple advertising service API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
