basePath: /api/v1
definitions:
  domain.Ad:
    properties:
      content:
        type: string
      id:
        type: integer
      price:
        type: integer
      title:
        type: string
    type: object
host: localhost:5000
info:
  contact: {}
  description: This is a simple advertising service API
  title: Advertising ServiceAPI
  version: "1.0"
paths:
  /ads:
    post:
      consumes:
      - application/json
      description: Create a new ad
      parameters:
      - description: Ad object that needs to be added
        in: body
        name: ad
        required: true
        schema:
          $ref: '#/definitions/domain.Ad'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Ad'
      summary: Create a new ad
      tags:
      - ads
swagger: "2.0"
