// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/huhuhu0420/simple-ad-service/domain"
	mock "github.com/stretchr/testify/mock"
)

// AdService is an autogenerated mock type for the AdService type
type AdService struct {
	mock.Mock
}

// CreateAd provides a mock function with given fields: ad, conditions
func (_m *AdService) CreateAd(ad domain.AdInfo, conditions domain.Conditions) error {
	ret := _m.Called(ad, conditions)

	if len(ret) == 0 {
		panic("no return value specified for CreateAd")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.AdInfo, domain.Conditions) error); ok {
		r0 = rf(ad, conditions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAd provides a mock function with given fields: searchAdRequest
func (_m *AdService) GetAd(searchAdRequest domain.SearchAdRequest) (*domain.AdsResponse, error) {
	ret := _m.Called(searchAdRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetAd")
	}

	var r0 *domain.AdsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.SearchAdRequest) (*domain.AdsResponse, error)); ok {
		return rf(searchAdRequest)
	}
	if rf, ok := ret.Get(0).(func(domain.SearchAdRequest) *domain.AdsResponse); ok {
		r0 = rf(searchAdRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AdsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.SearchAdRequest) error); ok {
		r1 = rf(searchAdRequest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAdService creates a new instance of AdService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdService {
	mock := &AdService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
