name: Docker Compose Actions Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy example.env
        run: cp example.env .env

      - name: Build the stack
        run: docker-compose up -d --build

      - name: Docker Compose Logs
        run: docker-compose logs

      - name: Test
        run: |
            for i in {1..10}; do
                curl -s -v --retry 10 --retry-connrefused http://localhost:5000/api/v1/ad && break || sleep 5
            done

      - name: newman api test
        uses: anthonyvscode/newman-action@v1.1
        with:
          collection: ./api-test/collection.json
          reporters: cli