name: Docker Compose Actions Workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy example.env
        run: cp example.env .env

      - name: Build the stack
        run: docker-compose up -d --build

      - name: Test
        run: curl -s -v --retry 10 --retry-connrefused http://localhost:5000/api/v1/ad