name: golang build and test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: golanci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: v1.54
        working-directory: ./

    - name: Build
      run: go build -v ./...

    - name: Test
      uses: robherley/go-test-action@v0.1.0