name: minikube-deploy
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v4
    - name: Start minikube
      uses: manusa/actions-setup-minikube@v2.10.0
      with:
        minikube version: 'v1.32.0'
        kubernetes version: 'v1.29.0'
    - name: Try the cluster !
      run: kubectl get nodes
    - name: Build image
      run: |
        docker build . -t go-server
        docker tag go-server huhuhu0420/go-server:latest
        echo -n "verifying images:"
        docker image ls       
    - name: Deploy to minikube
      run:
        kubectl create -f .
      working-directory: k8s
    - name: Test service 
      run: |
        minikube service list
        kubectl get ingress
